-- liquibase formatted sql

-- changeset Jason:1723793544028-1
-- preconditions onFail:WARN onError:MARK_RAN
-- precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM information_schema.tables where table_name = 'first_table'
-- comment: /* Comments should go after the precondition. Otherwise, Liquibase returns an error. */
CREATE TABLE "first_table" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 2) NOT NULL, "name" VARCHAR(225));

-- rollback drop table first_table;


-- changeset Jason:1723793544028-2
-- preconditions onFail:WARN onError:MARK_RAN
-- precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM information_schema.tables where table_name = 'articles'
-- comment: /* Comments should go after the precondition. Otherwise, Liquibase returns an error. */
CREATE TABLE "articles" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 11) NOT NULL, "title" VARCHAR(255) NOT NULL, "content" TEXT NOT NULL, "author" VARCHAR(100), "published_date" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(), "is_published" BOOLEAN DEFAULT FALSE, CONSTRAINT "articles_pkey" PRIMARY KEY ("id"));

-- changeset Jason:1723793544028-3
-- preconditions onFail:WARN onError:MARK_RAN
-- precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM information_schema.tables where table_name = 'comments'
-- comment: /* Comments should go after the precondition. Otherwise, Liquibase returns an error. */
CREATE TABLE "comments" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 51) NOT NULL, "article_id" INTEGER, "content" TEXT NOT NULL, "author" VARCHAR(100), "created_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(), CONSTRAINT "comments_pkey" PRIMARY KEY ("id"));
ALTER TABLE "comments" ADD CONSTRAINT "fk_article" FOREIGN KEY ("article_id") REFERENCES "articles" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset Jason:1723793544028-4
-- preconditions onFail:WARN onError:MARK_RAN
-- precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM articles
INSERT INTO articles (title, content, author, published_date, is_published)
VALUES ('The Impact of Artificial Intelligence on Healthcare',
        'This article explores how artificial intelligence is transforming the healthcare industry, from diagnostics to treatment planning, and the ethical considerations that come with it.',
        'Alice Johnson',
        '2024-09-01 10:00:00',
        TRUE
       );
